#cloud-config
packages:
  - python3-pip
  - python3-venv
  - unzip 
  - curl

package_update: true
package_upgrade: true

runcmd: 
  - cd /opt
  - git clone "https://github.com/chang432/general.git"

  - reboot

  - chmod +x /opt/general/startup.sh
  - (crontab -l 2>/dev/null; echo "*/1 * * * * /opt/general/startup.sh >> /var/log/startup.log 2>&1") | crontab -